### ISSUE TITLE
请问config.json里的"email"这一项有实际用处么？

### ISSUE THREAD

**Issue by FierceKing** [atrandys/v2ray-ws-tls#1]
https://github.com/atrandys/v2ray-ws-tls/blob/fbb1f2298719fd96cf9e494bd8b8f1f6e13d8385/config.json#L17

这个地方有一行 "email": "akcp1234@gmail.com"
我在手册里没找到这个值的解释，难道是有混淆的作用？

多些大神的脚本，server已经跑起来了，跑的飞快！

**Comment by atrandys** [comment]
没用，官方应该是用来区分统计流量。
