### ISSUE TITLE
可以使用Cloudflare DNS 验证吗？

### ISSUE THREAD

**Issue by cary-sas** [atrandys/v2ray-ws-tls#14]
你好，可以使用新的 CloudFlare API 令牌(Token)，自己输入CF_token值，然后获得证书吗？ （或者说需要这么做吗）

**Comment by ZqinKing** [comment]
> 你好，可以使用新的 CloudFlare API 令牌(Token)，自己输入CF_token值，然后获得证书吗？ （或者说需要这么做吗）

不需要。cf_dns那个还要安装别的东西的，VPS都有独立的公网IP，直接开放80或者443端口就能验证，拿到证书
